[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "gn-kernels"
version = "0.0.1"
dependencies = [
    "nvidia-cutlass-dsl[cu13]==4.7.0",
    "apache-tvm-ffi",
]

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
include = ["gn_kernels*"]

[tool.setuptools.package-data]
gn_kernels = ["**/*.cu", "**/*.h"]

[tool.ruff]
line-length = 120
extend-exclude = ["*.ipynb"]

[tool.ruff.lint]
extend-select = ["I"]
ignore = ["F401"]
